version: 0.0
os: linux
files:
  - source: /
    destination: /opt/codedeploy-agent/deployment-root/
hooks:

  AfterInstall:
    - location: scripts/start_container.sh
      timeout: 30
      runas: root
